//
//  SignsData.m
//  TrafficLawsKazakhstan
//
//  Created by Eugene Rozhkov on 09.03.15.
//  Copyright (c) 2015 Nord Point. All rights reserved.
//

#import "SignsData.h"

@implementation SignsData

+ (NSArray *) getSignsTypes
{
    NSMutableArray *signTypes = [@[] mutableCopy];
    
    [signTypes addObject:@{TYPE_NUMBER: @"1", TYPE_CODE:@"Warning", TYPE_NAME: @"Предупреждающие знаки", TYPE_IMAGE_NAME: @"Warning.png"}];
    [signTypes addObject:@{TYPE_NUMBER: @"2", TYPE_CODE:@"Priority", TYPE_NAME: @"Знаки приоритета", TYPE_IMAGE_NAME: @"Priority.png"}];
    [signTypes addObject:@{TYPE_NUMBER: @"3", TYPE_CODE:@"Denial", TYPE_NAME: @"Запрещающие знаки", TYPE_IMAGE_NAME: @"Denial.png"}];
    [signTypes addObject:@{TYPE_NUMBER: @"4", TYPE_CODE:@"Dictating", TYPE_NAME: @"Предписывающие знаки", TYPE_IMAGE_NAME: @"Dictating.png"}];
    [signTypes addObject:@{TYPE_NUMBER: @"5", TYPE_CODE:@"Information", TYPE_NAME: @"Информационно-указательные знаки", TYPE_IMAGE_NAME: @"Information.png"}];
    [signTypes addObject:@{TYPE_NUMBER: @"6", TYPE_CODE:@"Service", TYPE_NAME: @"Знаки сервиса", TYPE_IMAGE_NAME: @"Service.png"}];
    [signTypes addObject:@{TYPE_NUMBER: @"7", TYPE_CODE:@"Addition", TYPE_NAME: @"Знаки дополнительной информации (таблички)", TYPE_IMAGE_NAME: @"Addition.png"}];

    return [signTypes copy];
}

+ (NSDictionary *) getGroupByCode:(NSString *)groupCode
{
    NSArray *allTheGroups = [self getSignsTypes];
    for (NSDictionary *currentGroup in allTheGroups)
    {
        if ([currentGroup[TYPE_CODE] isEqualToString:groupCode])
        {
            return currentGroup;
        }
    }
    
    return nil;
}

+ (NSArray *) getAllTheSigns
{
    NSMutableArray *allTheSigns = [@[] mutableCopy];
    
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Железнодорожный переезд со шлагбаумом»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.2", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Железнодорожный переезд без шлагбаума»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.3.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Однопутная железная дорога»", SIGN_DESCRIPTION: @"Обозначение необорудованного шлагбаумом переезда через железную дорогу с одним путем", SIGN_IMAGE_NAME: @"1_3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.3.2", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Многопутная железная дорога»", SIGN_DESCRIPTION: @"Обозначение необорудованного шлагбаумом переезда через железную дорогу с двумя путями и более.", SIGN_IMAGE_NAME: @"1_3_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Приближение к железнодорожному переезду»", SIGN_DESCRIPTION: @"Дополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.2", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Приближение к железнодорожному переезду»", SIGN_DESCRIPTION: @"Дополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.3", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Приближение к железнодорожному переезду»", SIGN_DESCRIPTION: @"Дополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.4", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Приближение к железнодорожному переезду»", SIGN_DESCRIPTION: @"Дополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.5", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Приближение к железнодорожному переезду»", SIGN_DESCRIPTION: @"Дополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.6", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Приближение к железнодорожному переезду»", SIGN_DESCRIPTION: @"Дополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.5", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Пересечение с трамвайной линией»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.6", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Пересечение равнозначных дорог»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.7", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Пересечение с круговым движением»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.8", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Светофорное регулирование»", SIGN_DESCRIPTION: @"Перекресток, пешеходный переход или участок дороги, движение на котором регулируется светофором.", SIGN_IMAGE_NAME: @"1_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.9", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Разводной мост»", SIGN_DESCRIPTION: @"Разводной мост или паромная переправа", SIGN_IMAGE_NAME: @"1_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.10", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Выезд на набережную»", SIGN_DESCRIPTION: @"Выезд на набережную или берег.", SIGN_IMAGE_NAME: @"1_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.11.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Опасный поворот направо»", SIGN_DESCRIPTION: @"Закругление дороги малого радиуса или с ограниченной видимостью.", SIGN_IMAGE_NAME: @"1_11_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.11.2", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Опасный поворот налево»", SIGN_DESCRIPTION: @"Закругление дороги малого радиуса или с ограниченной видимостью.", SIGN_IMAGE_NAME: @"1_11_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.12.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Опасные повороты»", SIGN_DESCRIPTION: @"Участок дороги с опасными поворотами с первым поворотом направо.", SIGN_IMAGE_NAME: @"1_12_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.12.2", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Опасные повороты»", SIGN_DESCRIPTION: @"Участок дороги с опасными поворотами с первым поворотом налево.", SIGN_IMAGE_NAME: @"1_12_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.13", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Крутой спуск»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.14", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Крутой подъем»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_14.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.15", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Скользкая дорога»", SIGN_DESCRIPTION: @"Участок дороги с повышенной скользкостью проезжей части.", SIGN_IMAGE_NAME: @"1_15.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.16", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Неровная дорога»", SIGN_DESCRIPTION: @"Участок дороги, имеющий неровности на проезжей части (волнистость, выбоины, неплавные сопряжения с мостами и тому подобное).", SIGN_IMAGE_NAME: @"1_16.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.16.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Искусственная неровность»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_16_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.17", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Выброс гравия»", SIGN_DESCRIPTION: @"Участок дороги, на котором возможен выброс гравия, щебня и тому подобного из-под колес транспортных средств.", SIGN_IMAGE_NAME: @"1_17.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.18.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Сужение дороги»", SIGN_DESCRIPTION: @"Сужение с обеих сторон", SIGN_IMAGE_NAME: @"1_18_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.18.2", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Сужение дороги»", SIGN_DESCRIPTION: @"Сужение справа", SIGN_IMAGE_NAME: @"1_18_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.18.3", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Сужение дороги»", SIGN_DESCRIPTION: @"Сужение слева", SIGN_IMAGE_NAME: @"1_18_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.19", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Двустороннее движение»", SIGN_DESCRIPTION: @"Начало участка дороги (проезжей части) с встречным движением.", SIGN_IMAGE_NAME: @"1_19.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.20", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Пешеходный переход»", SIGN_DESCRIPTION: @"Пешеходный переход, обозначенный знаками 5.16.1, 5.16.2и (или) разметкой 1.14.1, 1.14.2 или 1.14.3.", SIGN_IMAGE_NAME: @"1_20.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.21", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Дети»", SIGN_DESCRIPTION: @"Участок дороги вблизи детского учреждения (школы, оздоровительного лагеря и тому подобного), на проезжей части которого возможно появление детей.", SIGN_IMAGE_NAME: @"1_21.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.22", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Пересечение с велосипедной дорожкой»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_22.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.23", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Дорожные работы»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_23.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.24", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Перегон скота»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_24.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.25", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Дикие животные»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_25.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.26", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Падение камней»", SIGN_DESCRIPTION: @"Участок дороги, на котором возможны обвалы, оползни, падение камней.", SIGN_IMAGE_NAME: @"1_26.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.27", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Боковой ветер»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_27.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.28", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Низколетящие самолеты»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_28.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.29", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Тоннель»", SIGN_DESCRIPTION: @"Тоннель, в котором отсутствует искусственное освещение, или тоннель, видимость въездного портала которого ограничена.", SIGN_IMAGE_NAME: @"1_29.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.30", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Прочие опасности»", SIGN_DESCRIPTION: @"Участок дороги, на котором имеются опасности, не предусмотренные другими предупреждающими знаками.", SIGN_IMAGE_NAME: @"1_30.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Направление поворота»", SIGN_DESCRIPTION: @"Направление движения на закруглении дороги малого радиуса с ограниченной видимостью. Направление объезда ремонтируемого участка дороги.", SIGN_IMAGE_NAME: @"1_31_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.2", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Направление поворота»", SIGN_DESCRIPTION: @"Направление движения на закруглении дороги малого радиуса с ограниченной видимостью. Направление объезда ремонтируемого участка дороги.", SIGN_IMAGE_NAME: @"1_31_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.3", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Направление поворота»", SIGN_DESCRIPTION: @"Направления движения на Т-образном перекрестке или разветвлении дорог. Направления объезда ремонтируемого участка дороги.", SIGN_IMAGE_NAME: @"1_31_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.4", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Направление поворота»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_31_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.5", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Направление поворота»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_31_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.32.1", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Объезд препятствия»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_32_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.32.2", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Объезд препятствия»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_32_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.32.3", SIGN_TYPE:@"Warning", SIGN_TITLE:@"«Объезд препятствия»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"1_32_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.1", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Главная дорога»", SIGN_DESCRIPTION: @"Дорога, на которой предоставлено право преимущественного проезда нерегулируемых перекрестков.", SIGN_IMAGE_NAME: @"2_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.2", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Конец главной дороги»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"2_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.3.1", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Пересечение со второстепенной дорогой»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"2_3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.3.2", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Примыкание второстепенной дороги справа»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"2_3_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.3.3", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Примыкание второстепенной дороги слева»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"2_3_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.4", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Уступите дорогу»", SIGN_DESCRIPTION: @"Водитель должен уступить дорогу транспортным средствам, движущимся по пересекаемой дороге, а при наличии таблички 7.13 — по главной.", SIGN_IMAGE_NAME: @"2_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.5", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Движение без остановки запрещено»", SIGN_DESCRIPTION: @"Запрещается движение без остановки перед стоп-линией, а если ее нет — перед краем пересекаемой проезжей части. Водитель должен уступить дорогу транспортным средствам, движущимся по пересекаемой дороге, а при наличии таблички 7.13 — по главной.\nЗнак 2.5 может быть установлен перед железнодорожным переездом или карантинным постом. В этих случаях водитель должен остановиться перед стоп-линией, а при ее отсутствии — перед знаком.", SIGN_IMAGE_NAME: @"2_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.6", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Преимущество встречного движения»", SIGN_DESCRIPTION: @"Запрещается въезд на узкий участок дороги, если это может затруднить встречное движение. Водитель должен уступить дорогу встречным транспортным средствам, находящимся на узком участке или противоположном подъезде к нему.", SIGN_IMAGE_NAME: @"2_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.7", SIGN_TYPE:@"Priority", SIGN_TITLE:@"«Преимущество перед встречным движением»", SIGN_DESCRIPTION: @"Узкий участок дороги, при движении по которому водитель пользуется преимуществом по отношению к встречным транспортным средствам.", SIGN_IMAGE_NAME: @"2_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.1", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Въезд запрещен»", SIGN_DESCRIPTION: @"Запрещается въезд всех транспортных средств в данном направлении.", SIGN_IMAGE_NAME: @"3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.2", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение запрещено»", SIGN_DESCRIPTION: @"Запрещается движение всех транспортных средств.", SIGN_IMAGE_NAME: @"3_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.3", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение механических транспортных средств запрещено»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.4", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение грузовых автомобилей запрещено»", SIGN_DESCRIPTION: @"Запрещается движение грузовых автомобилей и составов транспортных средств с разрешенной максимальной массой более 3,5 т (если на знаке не указана масса) или с разрешенной максимальной массой более указанной на знаке, а также тракторов и самоходных машин.\nЗнак 3.4 не запрещает движение грузовых автомобилей с наклонной белой полосой на бортах или предназначенных для перевозки людей.", SIGN_IMAGE_NAME: @"3_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.5", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение мотоциклов запрещено»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.6", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение тракторов запрещено»", SIGN_DESCRIPTION: @"Запрещается движение тракторов и самоходных машин.", SIGN_IMAGE_NAME: @"3_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.7", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение транспортных средств с прицепом запрещено»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.8", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение гужевых повозок запрещено»", SIGN_DESCRIPTION: @"Запрещается движение гужевых повозок (саней), верховых и вьючных животных, а также прогон скота.", SIGN_IMAGE_NAME: @"3_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.9", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение на велосипедах запрещено»", SIGN_DESCRIPTION: @"Запрещается движение велосипедов и мопедов.", SIGN_IMAGE_NAME: @"3_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.10", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение пешеходов запрещено»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.11", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Ограничение массы»", SIGN_DESCRIPTION: @"Запрещается движение транспортных средств, в том числе составов транспортных средств, общая фактическая масса которых больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_11.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.12", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Ограничение нагрузки на ось»", SIGN_DESCRIPTION: @"Запрещается движение транспортных средств, у которых фактическая нагрузка на какую-либо ось больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_12.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.13", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Ограничение высоты»", SIGN_DESCRIPTION: @"Запрещается движение транспортных средств, габаритная высота которых (с грузом или без груза) больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.14", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Ограничение ширины»", SIGN_DESCRIPTION: @"Запрещается движение транспортных средств, габаритная ширина которых (с грузом или без груза) больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_14.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.15", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Ограничение длины»", SIGN_DESCRIPTION: @"Запрещается движение транспортных средств (составов транспортных средств), габаритная длина которых (с грузом или без груза) больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_15.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.16", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Ограничение минимальной дистанции»", SIGN_DESCRIPTION: @"Запрещается движение транспортных средств с дистанцией между ними меньше указанной на знаке.", SIGN_IMAGE_NAME: @"3_16.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.17.1", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Таможня»", SIGN_DESCRIPTION: @"Запрещается проезд без остановки у таможни (контрольного пункта).", SIGN_IMAGE_NAME: @"3_17_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.17.2", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Опасность»", SIGN_DESCRIPTION: @"Запрещается дальнейшее движение всех без исключения транспортных средств в связи с дорожно-транспортным происшествием, аварией или другой опасностью.", SIGN_IMAGE_NAME: @"3_17_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.18.1", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Поворот направо запрещен»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_18_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.18.2", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Поворот налево запрещен»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_18_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.19", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Разворот запрещен»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_19.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.20", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Обгон запрещен»", SIGN_DESCRIPTION: @"Запрещается обгон всех транспортных средств, кроме одиночных, движущихся со скоростью менее 30 км/ч.", SIGN_IMAGE_NAME: @"3_20.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.21", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Конец зоны запрещения обгона»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_21.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.22", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Обгон грузовым автомобилям запрещен»", SIGN_DESCRIPTION: @"Запрещается грузовым автомобилям с разрешенной максимальной массой более 3,5 т обгон всех транспортных средств, кроме одиночных, движущихся со скоростью менее 30 км/ч. Тракторам запрещается обгон всех транспортных средств, кроме гужевых повозок и велосипедов.", SIGN_IMAGE_NAME: @"3_22.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.23", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Конец зоны запрещения обгона грузовым автомобилям»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_23.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.24", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Ограничение максимальной скорости»", SIGN_DESCRIPTION: @"Запрещается движение со скоростью (км/ч), превышающей указанную на знаке.", SIGN_IMAGE_NAME: @"3_24.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.25", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Конец зоны ограничения максимальной скорости»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"3_25.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.26", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Подача звукового сигнала запрещена»", SIGN_DESCRIPTION: @"Запрещается пользоваться звуковыми сигналами, кроме тех случаев, когда сигнал подается для предотвращения дорожно-транспортного происшествия.", SIGN_IMAGE_NAME: @"3_26.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.27", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Остановка запрещена»", SIGN_DESCRIPTION: @"Запрещаются остановка и стоянка транспортных средств.", SIGN_IMAGE_NAME: @"3_27.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.28", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Стоянка запрещена»", SIGN_DESCRIPTION: @"Запрещается стоянка транспортных средств.", SIGN_IMAGE_NAME: @"3_28.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.29", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Стоянка запрещена по нечетным числам месяца»", SIGN_DESCRIPTION: @"При одновременном применении знаков 3.29 и 3.30 время перестановки транспортных средств с одной стороны на другую — с 19 до 21 часа\n", SIGN_IMAGE_NAME: @"3_29.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.30", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Стоянка запрещена по четным числам месяца»", SIGN_DESCRIPTION: @"При одновременном применении знаков 3.29 и 3.30 время перестановки транспортных средств с одной стороны на другую — с 19 до 21 часа\n", SIGN_IMAGE_NAME: @"3_30.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.31", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Конец зоны всех ограничений»", SIGN_DESCRIPTION: @"Обозначение конца зоны действия одновременно несколькими знаками из следующих: 3.16, 3.20, 3.22, 3.24, 3.26-3.30.", SIGN_IMAGE_NAME: @"3_31.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.32", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение транспортных средств с опасными грузами запрещено»", SIGN_DESCRIPTION: @"Запрещается движение транспортных средств, оборудованных опознавательными знаками «Опасный груз».", SIGN_IMAGE_NAME: @"3_32.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.33", SIGN_TYPE:@"Denial", SIGN_TITLE:@"«Движение транспортных средств со взрывчатыми и легковоспламеняющимися грузами запрещено»", SIGN_DESCRIPTION: @"Запрещается движение транспортных средств, оборудованных опознавательными знаками «Опасный груз» и предназначенных для перевозки опасных грузов классов 1,2.2-2.4, 3.1, 3.2, 5.2 по ГОСТу 19433-88.", SIGN_IMAGE_NAME: @"3_33.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.1", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Движение прямо»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"4_1_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.2", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Движение направо»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"4_1_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.3", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Движение налево»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"4_1_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.4", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Движение прямо или направо»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"4_1_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.5", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Движение прямо или налево»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"4_1_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.6", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Движение направо или налево»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"4_1_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.2.1", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Объезд препятствия справа»", SIGN_DESCRIPTION: @"Объезд разрешается только со стороны, указанной стрелкой.", SIGN_IMAGE_NAME: @"4_2_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.2.2", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Объезд препятствия слева»", SIGN_DESCRIPTION: @"Объезд разрешается только со стороны, указанной стрелкой.", SIGN_IMAGE_NAME: @"4_2_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.2.3", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Объезд препятствия справа или слева»", SIGN_DESCRIPTION: @"Объезд разрешается с любой стороны.", SIGN_IMAGE_NAME: @"4_2_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.3", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Круговое движение»", SIGN_DESCRIPTION: @"Разрешается движение в указанном стрелками направлении.", SIGN_IMAGE_NAME: @"4_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.4", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Движение легковых автомобилей»", SIGN_DESCRIPTION: @"Разрешается движение легковых автомобилей, автобусов, мотоциклов, маршрутных транспортных средств и грузовых автомобилей, разрешенная максимальная масса которых не превышает 3,5 т.\nЗнак разрешает движение и других транспортных средств, которые обслуживают предприятия, находящиеся в обозначенной зоне, а также обслуживают граждан или принадлежат гражданам, проживающим или работающим в обозначенной зоне. В этих случаях транспортные средства должны въезжать в обозначенную зону и выезжать из нее на ближайшем к месту назначения перекрестке.", SIGN_IMAGE_NAME: @"4_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.5", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Велосипедная дорожка»", SIGN_DESCRIPTION: @"Разрешается движение только на велосипедах и мопедах. По велосипедной дорожке могут двигаться также пешеходы (при отсутствии тротуара, пешеходной дорожки или обочины).", SIGN_IMAGE_NAME: @"4_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.6", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Пешеходная дорожка»", SIGN_DESCRIPTION: @"Разрешается движение только пешеходам.", SIGN_IMAGE_NAME: @"4_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.7", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Ограничение минимальной скорости»", SIGN_DESCRIPTION: @"Разрешается движение только с указанной или большей скоростью (км/ч).", SIGN_IMAGE_NAME: @"4_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.8", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Конец зоны ограничения минимальной скорости»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"4_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.9.1", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Направление движения транспортных средств с опасными грузами»", SIGN_DESCRIPTION: @"Движение транспортных средств, оборудованных опознавательными знаками «Опасный груз», разрешается только направо.", SIGN_IMAGE_NAME: @"4_9_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.9.2", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Направление движения транспортных средств с опасными грузами»", SIGN_DESCRIPTION: @"Движение транспортных средств, оборудованных опознавательными знаками «Опасный груз», разрешается только налево.", SIGN_IMAGE_NAME: @"4_9_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.9.3", SIGN_TYPE:@"Dictating", SIGN_TITLE:@"«Направление движения транспортных средств с опасными грузами»", SIGN_DESCRIPTION: @"Движение транспортных средств, оборудованных опознавательными знаками «Опасный груз», разрешается только прямо.", SIGN_IMAGE_NAME: @"4_9_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Автомагистраль»", SIGN_DESCRIPTION: @"Дорога, на которой действуют требования Правил, устанавливающие порядок движения по автомагистралям.", SIGN_IMAGE_NAME: @"5_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец автомагистрали»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.3", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Дорога для автомобилей»", SIGN_DESCRIPTION: @"Дорога, предназначенная для движения только автомобилей и мотоциклов.", SIGN_IMAGE_NAME: @"5_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.4", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец дороги для автомобилей»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.5", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Дорога с односторонним движением»", SIGN_DESCRIPTION: @"Дорога или проезжая часть, по которой движение транспортных средств по всей ширине осуществляется в одном направлении.", SIGN_IMAGE_NAME: @"5_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.6", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец дороги с односторонним движением»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.7.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Выезд на дорогу с односторонним движением»", SIGN_DESCRIPTION: @"Выезд на дорогу или проезжую часть с односторонним движением.\n", SIGN_IMAGE_NAME: @"5_7_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.7.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Выезд на дорогу с односторонним движением»", SIGN_DESCRIPTION: @"Выезд на дорогу или проезжую часть с односторонним движением.\n", SIGN_IMAGE_NAME: @"5_7_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направления движения по полосам»", SIGN_DESCRIPTION: @"Число полос и разрешенные направления движения на каждой из них.", SIGN_IMAGE_NAME: @"5_8_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направления движения по полосе»", SIGN_DESCRIPTION: @"Разрешенные направления движения по полосе.\nЗнаки 5.8.1 и 5.8.2, разрешающие поворот налево из крайней левой полосы, разрешают и разворот с этой полосы.\nДействие знаков 5.8.1 и 5.8.2, установленных перед перекрестком, распространяется на весь перекресток, если другие знаки 5.8.1 и 5.8.2, установленные на нем, не дают иных указаний.", SIGN_IMAGE_NAME: @"5_8_2_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.3", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Начало полосы»", SIGN_DESCRIPTION: @"Начало дополнительной полосы на подъеме или полосы торможения.\nЕсли на знаке, установленном перед дополнительной полосой, изображен знак 4.7 «Ограничение минимальной скорости», то водитель транспортного средства, который не может продолжать движение по основной полосе с указанной или большей скоростью, должен перестроиться на дополнительную полосу", SIGN_IMAGE_NAME: @"5_8_3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.4", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Начало полосы»", SIGN_DESCRIPTION: @"Начало участка средней полосы трехполосной дороги, предназначенного для движения в данном направлении.", SIGN_IMAGE_NAME: @"5_8_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.5", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец полосы»", SIGN_DESCRIPTION: @"Конец дополнительной полосы на подъеме или полосы разгона.", SIGN_IMAGE_NAME: @"5_8_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.6", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец полосы»", SIGN_DESCRIPTION: @"Конец участка средней полосы на трехполосной дороге, предназначенного для движения в данном направлении.", SIGN_IMAGE_NAME: @"5_8_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.7", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направление движения по полосам»", SIGN_DESCRIPTION: @"Если на знаке 5.8.7 изображен знак, запрещающий движение каким-либо транспортным средствам, то движение этих транспортных средств по соответствующей полосе запрещается.\nЗнаки 5.8.7 и 5.8.8 с соответствующим числом стрелок могут применяться на дорогах с четырьмя полосами и более.\nС помощью знаков 5.8.7 и 5.8.8 со сменным изображением может быть организовано реверсивное движение.\n", SIGN_IMAGE_NAME: @"5_8_7_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.8", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направление движения по полосам»", SIGN_DESCRIPTION: @"Если на знаке 5.8.7 изображен знак, запрещающий движение каким-либо транспортным средствам, то движение этих транспортных средств по соответствующей полосе запрещается.\nЗнаки 5.8.7 и 5.8.8 с соответствующим числом стрелок могут применяться на дорогах с четырьмя полосами и более.\nС помощью знаков 5.8.7 и 5.8.8 со сменным изображением может быть организовано реверсивное движение.\n", SIGN_IMAGE_NAME: @"5_8_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.9", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Полоса для маршрутных транспортных средств»", SIGN_DESCRIPTION: @"Полоса, предназначенная для движения только маршрутных транспортных средств, движущихся попутно общему потоку транспортных средств.\nДействие знака распространяется на полосу, над которой он расположен. Действие знака, установленного справа от дороги, распространяется на правую полосу.", SIGN_IMAGE_NAME: @"5_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.10.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Дорога с полосой для маршрутных транспортных средств»", SIGN_DESCRIPTION: @"Дорога, по которой движение маршрутных транспортных средств осуществляется по специально выделенной полосе навстречу общему потоку транспортных средств.", SIGN_IMAGE_NAME: @"5_10_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.10.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Выезд на дорогу с полосой для маршрутных транспортных средств»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_10_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.10.3", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Выезд на дорогу с полосой для маршрутных транспортных средств»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_10_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.10.4", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец дороги с полосой для маршрутных транспортных средств»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_10_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.11.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Место для разворота»", SIGN_DESCRIPTION: @"Поворот налево запрещается.", SIGN_IMAGE_NAME: @"5_11_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.11.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Зона для разворота»", SIGN_DESCRIPTION: @"Протяженность зоны для разворота. Поворот налево запрещается.", SIGN_IMAGE_NAME: @"5_11_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.12", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Место остановки автобуса и (или) троллейбуса»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_12.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.13", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Место остановки трамвая»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.14", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Место стоянки легковых такси»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_14.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.15", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Место стоянки»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_15.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.16.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Пешеходный переход»", SIGN_DESCRIPTION: @"При отсутствии на переходе разметки 1.14.1, 1.14.2 или1.14.3 знак 5.16.2 устанавливается справа от дороги на ближней границе перехода, а знак 5.16.1 — слева от дороги на дальней границе перехода.\n", SIGN_IMAGE_NAME: @"5_16_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.16.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Пешеходный переход»", SIGN_DESCRIPTION: @"При отсутствии на переходе разметки 1.14.1, 1.14.2 или1.14.3 знак 5.16.2 устанавливается справа от дороги на ближней границе перехода, а знак 5.16.1 — слева от дороги на дальней границе перехода.\n", SIGN_IMAGE_NAME: @"5_16_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.17.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Подземный пешеходный переход»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_17_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.17.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Подземный пешеходный переход»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_17_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.17.3", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Надземный пешеходный переход»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_17_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.17.4", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Надземный пешеходный переход»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_17_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.18", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Рекомендуемая скорость»", SIGN_DESCRIPTION: @"Скорость, с которой рекомендуется движение на данном участке дороги. Зона действия знака распространяется до ближайшего перекрестка, а при применении знака 5.18 совместно с предупреждающим знаком определяется протяженностью опасного участка.", SIGN_IMAGE_NAME: @"5_18.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.19.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Тупик»", SIGN_DESCRIPTION: @"Дорога, не имеющая сквозной проезд.\n", SIGN_IMAGE_NAME: @"5_19_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.19.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Тупик»", SIGN_DESCRIPTION: @"Дорога, не имеющая сквозной проезд.\n", SIGN_IMAGE_NAME: @"5_19_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.19.3", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Тупик»", SIGN_DESCRIPTION: @"Дорога, не имеющая сквозной проезд.\n", SIGN_IMAGE_NAME: @"5_19_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.20.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Предварительный указатель направления»", SIGN_DESCRIPTION: @"Направления движения к обозначенным на знаке населенным пунктам и другим объектам. На знаках могут быть нанесены изображения знака 5.29.1, символы автомагистрали, аэропорта, спортивные и иные пиктограммы.\nНа знаке 5.20.1 могут быть нанесены изображения других знаков, информирующих об особенностях движения. В нижней части знака 5.20.1 указывается расстояние от места установки знака до перекрестка или начала полосы торможения.\nЗнак 5.20.1 применяется также для указания объезда участков дорог, на которых установлен один из запрещающих знаков 3.11-3.15.", SIGN_IMAGE_NAME: @"5_20_1_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.20.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Предварительный указатель направления»", SIGN_DESCRIPTION: @"Направления движения к обозначенным на знаке населенным пунктам и другим объектам. На знаках могут быть нанесены изображения знака 5.29.1, символы автомагистрали, аэропорта, спортивные и иные пиктограммы.\nНа знаке 5.20.1 могут быть нанесены изображения других знаков, информирующих об особенностях движения. В нижней части знака 5.20.1 указывается расстояние от места установки знака до перекрестка или начала полосы торможения.\nЗнак 5.20.1 применяется также для указания объезда участков дорог, на которых установлен один из запрещающих знаков 3.11-3.15.", SIGN_IMAGE_NAME: @"5_20_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.20.3", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Схема движения»", SIGN_DESCRIPTION: @"Маршрут движения при запрещении на перекрестке отдельных маневров или разрешенные направления движения на сложном перекрестке.", SIGN_IMAGE_NAME: @"5_20_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.21.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Указатель направлений»", SIGN_DESCRIPTION: @"Направления движения к пунктам маршрута. На знаках может быть указано расстояние до обозначенных на нем объектов (км), нанесены символы автомагистрали, аэропорта, спортивные и иные пиктограммы.", SIGN_IMAGE_NAME: @"5_21_1_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.21.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Указатель направлений»", SIGN_DESCRIPTION: @"Направления движения к пунктам маршрута. На знаках может быть указано расстояние до обозначенных на нем объектов (км), нанесены символы автомагистрали, аэропорта, спортивные и иные пиктограммы.", SIGN_IMAGE_NAME: @"5_21_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.22", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Начало населенного пункта»", SIGN_DESCRIPTION: @"Наименование и начало населенного пункта, в котором действуют требования Правил, устанавливающие порядок движения в населенных пунктах.", SIGN_IMAGE_NAME: @"5_22.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.23", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец населенного пункта»", SIGN_DESCRIPTION: @"Место, с которого на данной дороге утрачивают силу требования Правил, устанавливающие порядок движения в населенных пунктах.", SIGN_IMAGE_NAME: @"5_23.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.24", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Начало населенного пункта»", SIGN_DESCRIPTION: @"Наименование и начало населенного пункта, в котором на данной дороге не действуют требования Правил, устанавливающие порядок движения в населенных пунктах.", SIGN_IMAGE_NAME: @"5_24.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.25", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец населенного пункта»", SIGN_DESCRIPTION: @"Конец населенного пункта, обозначенного знаком 5.24.", SIGN_IMAGE_NAME: @"5_25.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.26", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Наименование объекта»", SIGN_DESCRIPTION: @"Наименование объекта иного, чем населенный пункт (река, озеро, перевал, достопримечательность и тому подобное).", SIGN_IMAGE_NAME: @"5_26_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.27", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Указатель расстояний»", SIGN_DESCRIPTION: @"Расстояние до населенных пунктов (км), расположенных на маршруте.", SIGN_IMAGE_NAME: @"5_27.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.28", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Километровый знак»", SIGN_DESCRIPTION: @"Расстояние до начала или конца дороги (км).", SIGN_IMAGE_NAME: @"5_28.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.29.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Номер маршрута»", SIGN_DESCRIPTION: @"Номер, присвоенный дороге (маршруту).", SIGN_IMAGE_NAME: @"5_29_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.29.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Номер маршрута»", SIGN_DESCRIPTION: @"Номер и направление дороги (маршрута).", SIGN_IMAGE_NAME: @"5_29_2_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.30.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направление движения для грузовых автомобилей»", SIGN_DESCRIPTION: @"Рекомендуемое направление движения для грузовых автомобилей, тракторов и самоходных машин, если на перекрестке их движение в одном из направлений запрещено.\n", SIGN_IMAGE_NAME: @"5_30_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.30.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направление движения для грузовых автомобилей»", SIGN_DESCRIPTION: @"Рекомендуемое направление движения для грузовых автомобилей, тракторов и самоходных машин, если на перекрестке их движение в одном из направлений запрещено.\n", SIGN_IMAGE_NAME: @"5_30_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.30.3", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направление движения для грузовых автомобилей»", SIGN_DESCRIPTION: @"Рекомендуемое направление движения для грузовых автомобилей, тракторов и самоходных машин, если на перекрестке их движение в одном из направлений запрещено.\n", SIGN_IMAGE_NAME: @"5_30_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.31", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Схема объезда»", SIGN_DESCRIPTION: @"Маршрут объезда участка дороги, временно закрытого для движения.", SIGN_IMAGE_NAME: @"5_31.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.32.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направление объезда»", SIGN_DESCRIPTION: @"Направление участка дороги, временно закрытого для движения.\n", SIGN_IMAGE_NAME: @"5_32_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.32.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направление объезда»", SIGN_DESCRIPTION: @"Направление участка дороги, временно закрытого для движения.\n", SIGN_IMAGE_NAME: @"5_32_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.32.3", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Направление объезда»", SIGN_DESCRIPTION: @"Направление участка дороги, временно закрытого для движения.\n", SIGN_IMAGE_NAME: @"5_32_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.33", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Стоп-линия»", SIGN_DESCRIPTION: @"Место остановки транспортных средств при запрещающем сигнале светофора (регулировщика).", SIGN_IMAGE_NAME: @"5_33.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.34.1", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Предварительный указатель перестроения на другую проезжую часть»", SIGN_DESCRIPTION: @"Направление объезда закрытого для движения участка проезжей части на дороге с разделительной полосой или направление движения для возвращения на правую проезжую часть.\n", SIGN_IMAGE_NAME: @"5_34_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.34.2", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Предварительный указатель перестроения на другую проезжую часть»", SIGN_DESCRIPTION: @"Направление объезда закрытого для движения участка проезжей части на дороге с разделительной полосой или направление движения для возвращения на правую проезжую часть.\n", SIGN_IMAGE_NAME: @"5_34_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.35", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Реверсивное движение»", SIGN_DESCRIPTION: @"Начало участка дороги, на котором на одной или нескольких полосах направление движения может изменяться на противоположное.", SIGN_IMAGE_NAME: @"5_35.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.36", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец реверсивного движения»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_36.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.37", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Выезд на дорогу с реверсивным движением»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_37.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.38", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Жилая зона»", SIGN_DESCRIPTION: @"Территория, на которой действуют требования Правил, устанавливающие порядок движения в жилой зоне.", SIGN_IMAGE_NAME: @"5_38.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.39", SIGN_TYPE:@"Information", SIGN_TITLE:@"«Конец жилой зоны»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"5_39.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.1", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Пункт первой медицинской помощи»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.2", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Больница»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.3", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Автозаправочная станция»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.4", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Техническое обслуживание автомобилей»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.5", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Мойка автомобилей»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.6", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Телефон»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.7", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Пункт питания»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.8", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Питьевая вода»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.9", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Гостиница или мотель»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.10", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Кемпинг»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.11", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Место отдыха»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_11.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.12", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Пост дорожной полиции»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_12.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.13", SIGN_TYPE:@"Service", SIGN_TITLE:@"«Пост транспортного контроля»", SIGN_DESCRIPTION: @"", SIGN_IMAGE_NAME: @"6_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.1.1", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Расстояние до объекта»", SIGN_DESCRIPTION: @"Указывается расстояние от знака до начала опасного участка, места введения соответствующего ограничения или определенного объекта (места), находящегося впереди по ходу движения.", SIGN_IMAGE_NAME: @"7_1_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.1.2", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Расстояние до объекта»", SIGN_DESCRIPTION: @"Указывает расстояние от знака 2.4 до перекрестка в случае, если непосредственно перед перекрестком установлен знак 2.5.", SIGN_IMAGE_NAME: @"7_1_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.1.3", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Расстояние до объекта»", SIGN_DESCRIPTION: @"Указывает расстояние до объекта, находящегося в стороне от дороги.", SIGN_IMAGE_NAME: @"7_1_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.1.4", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Расстояние до объекта»", SIGN_DESCRIPTION: @"Указывает расстояние до объекта, находящегося в стороне от дороги.", SIGN_IMAGE_NAME: @"7_1_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.1", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Зона действия»", SIGN_DESCRIPTION: @"Указывает протяженность опасного участка дороги, обозначенного знаками, или зону действия запрещающих и информационно-указательных знаков.", SIGN_IMAGE_NAME: @"7_2_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.2", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Зона действия»", SIGN_DESCRIPTION: @"Указывает зону действия запрещающих знаков 3.27, 3.28, 3.29 и 3.30.", SIGN_IMAGE_NAME: @"7_2_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.3", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Зона действия»", SIGN_DESCRIPTION: @"Указывает конец зоны действия знаков 3.27, 3.28, 3.29 и 3.30.", SIGN_IMAGE_NAME: @"7_2_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.4", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Зона действия»", SIGN_DESCRIPTION: @"Информирует водителей о нахождении их в зоне действия знаков 3.27,3.28, 3.29 и 3.30.", SIGN_IMAGE_NAME: @"7_2_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.5", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Зона действия»", SIGN_DESCRIPTION: @"Указывают направление и зону действия знаков 3.27, 3.28, 3.29 и 3.30при запрещении остановки или стоянки вдоль одной стороны площади, фасада здания и тому подобного.", SIGN_IMAGE_NAME: @"7_2_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.6", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Зона действия»", SIGN_DESCRIPTION: @"Указывают направление и зону действия знаков 3.27, 3.28, 3.29 и 3.30при запрещении остановки или стоянки вдоль одной стороны площади, фасада здания и тому подобного.", SIGN_IMAGE_NAME: @"7_2_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.3.1", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Направления действия»", SIGN_DESCRIPTION: @"Указывают направления действия знаков, установленных перед перекрестком, или направления движения к обозначенным объектам, находящимся непосредственно у дороги.", SIGN_IMAGE_NAME: @"7_3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.3.2", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Направления действия»", SIGN_DESCRIPTION: @"Указывают направления действия знаков, установленных перед перекрестком, или направления движения к обозначенным объектам, находящимся непосредственно у дороги.", SIGN_IMAGE_NAME: @"7_3_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.3.3", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Направления действия»", SIGN_DESCRIPTION: @"Указывают направления действия знаков, установленных перед перекрестком, или направления движения к обозначенным объектам, находящимся непосредственно у дороги.", SIGN_IMAGE_NAME: @"7_3_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.1", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Вид транспортного средства»", SIGN_DESCRIPTION: @"Указывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.2", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Вид транспортного средства»", SIGN_DESCRIPTION: @"Указывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.3", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Вид транспортного средства»", SIGN_DESCRIPTION: @"Указывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.4", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Вид транспортного средства»", SIGN_DESCRIPTION: @"Указывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.5", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Вид транспортного средства»", SIGN_DESCRIPTION: @"Указывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.6", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Вид транспортного средства»", SIGN_DESCRIPTION: @"Указывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.7", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Вид транспортного средства»", SIGN_DESCRIPTION: @"Указывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.8", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Вид транспортного средства»", SIGN_DESCRIPTION: @"Указывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.1", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Субботние, воскресные и праздничные дни»", SIGN_DESCRIPTION: @"Указывают дни недели, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.2", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Рабочие дни»", SIGN_DESCRIPTION: @"Указывают дни недели, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.3", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Дни недели»", SIGN_DESCRIPTION: @"Указывают дни недели, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.4", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Время действия»", SIGN_DESCRIPTION: @"Указывает время суток, в течение которого действует знак.", SIGN_IMAGE_NAME: @"7_5_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.5", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Время действия»", SIGN_DESCRIPTION: @"Указывают дни недели и время суток, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.6", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Время действия»", SIGN_DESCRIPTION: @"Указывают дни недели и время суток, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.7", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Время действия»", SIGN_DESCRIPTION: @"Указывают дни недели и время суток, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.1", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.2", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.3", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.4", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.5", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.6", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.7", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.8", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.9", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Способ постановки транспортного средства на стоянку»", SIGN_DESCRIPTION: @"7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.7", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Стоянка с неработающим двигателем»", SIGN_DESCRIPTION: @"Указывает, что на стоянке, обозначенной знаком 5.15, разрешается стоянка транспортных средств только с неработающим двигателем.", SIGN_IMAGE_NAME: @"7_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.8", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Платные услуги»", SIGN_DESCRIPTION: @"Указывает, что услуги предоставляются только за оплату.", SIGN_IMAGE_NAME: @"7_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.9", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Ограничение продолжительности стоянки»", SIGN_DESCRIPTION: @"Указывает максимальную продолжительность пребывания транспортного средства на стоянке, обозначенной знаком 5.15.", SIGN_IMAGE_NAME: @"7_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.10", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Место для осмотра автомобилей»", SIGN_DESCRIPTION: @"Указывает, что на площадке, обозначенной знаком 5.15 или 6.11, имеется эстакада или смотровая канава.", SIGN_IMAGE_NAME: @"7_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.11", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Ограничение полной массы»", SIGN_DESCRIPTION: @"Указывает, что действие знака распространяется только на транспортные средства с разрешенной максимальной массой более указанной на табличке.", SIGN_IMAGE_NAME: @"7_11.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.12", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Опасная обочина»", SIGN_DESCRIPTION: @"Предупреждает, что съезд на обочину опасен в связи с проведением на ней ремонтных работ. Применяется со знаком 1.23.", SIGN_IMAGE_NAME: @"7_12.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.13", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Направление главной дороги»", SIGN_DESCRIPTION: @"Указывает направление главной дороги на перекрестке.", SIGN_IMAGE_NAME: @"7_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.14", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Полоса движения»", SIGN_DESCRIPTION: @"Указывает полосу движения, на которую распространяется действие знака или светофора.", SIGN_IMAGE_NAME: @"7_14.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.15", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Слепые пешеходы»", SIGN_DESCRIPTION: @"Указывает, что пешеходным переходом пользуются слепые. Применяется со знаками 1.20, 5.16.1, 5.16.2 и светофорами.", SIGN_IMAGE_NAME: @"7_15.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.16", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Влажное покрытие»", SIGN_DESCRIPTION: @"Указывает, что действие знака распространяется на период времени, когда покрытие проезжей части влажное.", SIGN_IMAGE_NAME: @"7_16.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.17", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Инвалиды»", SIGN_DESCRIPTION: @"Указывает, что действие знака 5.15 распространяется только на мотоколяски и автомобили, на которых установлены опознавательные знаки «Инвалид»", SIGN_IMAGE_NAME: @"7_17.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.18", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Кроме инвалидов»", SIGN_DESCRIPTION: @"Указывает, что действие знаков не распространяется на мотоколяски и автомобили, на которых установлены опознавательные знаки «Инвалид»", SIGN_IMAGE_NAME: @"7_18.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.19", SIGN_TYPE:@"Addition", SIGN_TITLE:@"«Класс опасного груза»", SIGN_DESCRIPTION: @"Указывает номер класса (классов) опасных грузов по ГОСТу 19433-88. Применяется со знаками 3.32, 4.9.1-4.9.3\n", SIGN_IMAGE_NAME: @"7_19.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Автопоезд»", SIGN_DESCRIPTION: @"В виде трех фонарей оранжевого цвета, расположенных горизонтально на крыше кабины с промежутками между ними от 150 до 300 мм — на грузовых автомобилях и колесных тракторах (класса 1,4 и выше) с прицепами, а также на сочлененных автобусах и троллейбусах. Допускается применение опознавательных знаков автопоезда в виде равностороннего треугольника желтого цвета (сторона — 250 мм) с устройством для внутреннего освещения.", SIGN_IMAGE_NAME: @"p2_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Шипы»", SIGN_DESCRIPTION: @"В виде равностороннего треугольника белого цвета вершиной вверх с каймой красного цвета, в который вписана буква «Ш» черного цвета (сторона треугольника — не менее 200 мм, ширина каймы 1/10 стороны) — сзади механических транспортных средств, имеющих ошипованные шины.", SIGN_IMAGE_NAME: @"p2_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Перевозка детей»", SIGN_DESCRIPTION: @"В виде квадрата желтого цвета с каймой красного цвета (сторона не менее 250 мм, ширина каймы — 1/10 стороны), с черным изображением символа дорожного знака 1.21 спереди и сзади автобусов или грузовых автомобилей при перевозке групп детей.", SIGN_IMAGE_NAME: @"p2_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Глухой водитель»", SIGN_DESCRIPTION: @"В виде желтого круга диаметром 160 мм с нанесенными внутри тремя черными кружками диаметром 40 мм, расположенными по углам воображаемого равностороннего треугольника, вершина которого обращена вниз — спереди и сзади механических транспортных средств, управляемых глухонемыми или глухими водителями.", SIGN_IMAGE_NAME: @"p2_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Учебное транспортное средство»", SIGN_DESCRIPTION: @"В виде равностороннего треугольника белого цвета с вершиной вверх с каймой красного цвета, в который вписана буква «У» черного цвета (сторона — не менее 200 мм, ширина каймы — 1/10 стороны) — спереди и сзади механических транспортных средств, используемых для обучения вождению (допускается установка двустороннего знака на крыше легкового автомобиля).", SIGN_IMAGE_NAME: @"p2_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Ограничение скорости»", SIGN_DESCRIPTION: @"В виде уменьшенного цветного изображения дорожного знака 3.24 с указанием разрешенной скорости (диаметр знака — не менее 160 мм, ширина каймы — 1/10 диаметра) — на задней стороне кузова слева у механических транспортных средств, перевозящих тяжеловесные и крупногабаритные грузы, а также в случаях, когда максимальная скорость транспортного средства по технической характеристике ниже определенной пунктом 10.3 Правил.", SIGN_IMAGE_NAME: @"p2_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Опасный груз»", SIGN_DESCRIPTION: @"В виде прямоугольника, имеющего световозвращающую поверхность, соответствующую требованиям СТ РК ГОСТ Р 41.104-2001, размером 690×300 мм, правая часть которого размером 400×300 мм окрашена в оранжевый, а левая — в белый цвет с каймой черного цвета (ширина — 15 мм) и обозначениями, характеризующими опасные свойства груза (по ГОСТу 19433-88) — спереди и сзади транспортных средств, перевозящих такие грузы.", SIGN_IMAGE_NAME: @"p2_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Крупногабаритный груз»", SIGN_DESCRIPTION: @"В виде щитка размером 400×400 мм с нанесенными по диагонали красными и белыми чередующимися полосами шириной 50 мм со световозвращающей поверхностью, соответствующей требованиям ГОСТов СТ РК ГОСТ Р 51253-2001 и СТ РК ГОСТ Р 41.104-2001 — спереди, сзади и сбоку на крупногабаритном грузе.", SIGN_IMAGE_NAME: @"p2_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Длинномерное транспортное средство»", SIGN_DESCRIPTION: @"В виде прямоугольника размером не менее 1200×200 мм желтого цвета с каймой красного цвета (ширина — 40 мм), имеющего световозвращающую поверхность — сзади транспортных средств, длина которых (включая один прицеп) с грузом или без груза — более 20 м, и автопоездов с двумя и более прицепами. При невозможности размещения знака указанного размера допускается установка двух одинаковых знаков размером не менее 600×200 мм симметрично оси транспортного средства.", SIGN_IMAGE_NAME: @"p2_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Инвалид»", SIGN_DESCRIPTION: @"В виде квадрата желтого цвета со стороной 150 мм и изображением символа дорожного знака 7.17 черного цвета — спереди и сзади механических транспортных средств, управляемых инвалидами I и II групп или перевозящих таких инвалидов.", SIGN_IMAGE_NAME: @"p2_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"0", SIGN_TYPE:@"Identification", SIGN_TITLE:@"«Врач»", SIGN_DESCRIPTION: @"В виде квадрата синего цвета (сторона — 140 мм) со вписанным белым кругом (диаметр — 125 мм), на который нанесен красный крест (высота — 90 мм, ширина штриха — 25 мм) — спереди и сзади автомобиля, управляемого водителем — врачом.\nДанный опознавательный знак может быть установлен по желанию водителя.\n", SIGN_IMAGE_NAME: @"p2_11.png"}];

    
    return [allTheSigns copy];
}

+ (NSArray *) getSignsWithType:(NSString *)signType
{
    NSMutableArray *signs = [@[] mutableCopy];
    
    for (NSDictionary *currentSign in [self getAllTheSigns])
    {
        if ([currentSign[SIGN_TYPE] isEqualToString:signType])
             {
                 [signs addObject:currentSign];
             }
    }
    
    return [signs copy];
}

+ (NSDictionary *) getSignWithNumber:(NSString *)signNumber
{
    NSArray *allTheSigns = [self getAllTheSigns];
    for (NSDictionary *currentSign in allTheSigns)
    {
        if ([currentSign[SIGN_NUMBER] isEqualToString:signNumber])
        {
            return currentSign;
        }
    }
    
    return nil;
}

+ (NSArray *) getAllTheSignsInfo
{
    NSMutableArray *signsInfos = [@[] mutableCopy];
    
    [signsInfos addObject:@{TYPE_CODE:@"Warning",  GROUP_INFO_TEXT: @"Предупреждающие знаки 1.1, 1.2, 1.5-1.30 вне населенных пунктов устанавливаются на расстоянии 150 — 300 м, а в населенных пунктах и жилых зонах — на расстоянии 50 — 100 м до начала опасного участка. При необходимости знаки могут устанавливаться и на ином расстоянии, которое в этом случае указывается на табличке 7.1.1.\n\nЗнаки 1.13 и 1.14 могут устанавливаться без таблички 7.1.1 непосредственно перед началом спуска или подъема, если спуски и подъемы следуют друг за другом.\n\nЗнак 1.23 при проведении краткосрочных работ на проезжей части может быть установлен (без таблички 7.1.1) на расстоянии 10-15 м до места проведения работ.\n\nВне населенных пунктов знаки 1.1, 1.2, 1.9, 1.10, 1.21 и 1.23 повторяются. Второй знак устанавливается на расстоянии не менее 50 м до начала опасного участка.\n\nЗнаки 1.4.1 — 1.4.3 устанавливаются с правой стороны дороги, а знаки 1.4.4 — 1.4.6 — с левой. Знаки 1.4.1 и 1.4.4 — под первым по ходу движения знаком 1.1 или 1.2, знаки 1.4.3 и 1.4.6 — под вторым знаком 1.1 или 1.2, а знаки 1.4.2 и 1.4.5 — самостоятельно, на равном расстоянии между первым и вторым знаком 1.1 или 1.2.\n\nЗнаки 1.3.1 и 1.3.2 устанавливаются непосредственно перед железнодорожным переездом."}];
    [signsInfos addObject:@{TYPE_CODE:@"Denial",  GROUP_INFO_TEXT: @"Знаки 3.2-3.9, 3.32 и 3.33 запрещают движение соответствующих видов транспортных средств в обоих направлениях.\n\nДействие знаков не распространяется:\n\n3.1-3.3, 3.18.1, 3.18.2, 3.19, 3.27 — на маршрутные транспортные средства;\n3.2-3.8 — на транспортные средства, которые обслуживают предприятия, находящиеся в обозначенной зоне, а также обслуживают граждан или принадлежат гражданам, проживающим или работающим в обозначенной зоне. В этих случаях транспортные средства должны въезжать в обозначенную зону и выезжать из нее на ближайшем к месту назначения перекрестке;\n3.28-3.30 — на такси с включенным таксометром;\n3.2, 3.3, 3.28-3.30 — на транспортные средства, управляемые инвалидами I и II групп или перевозящие таких инвалидов.\nДействие знаков 3.18.1, 3.18.2 распространяется на пересечение проезжих частей, перед которым установлен знак.\n\nЗона действия знаков 3.16, 3.20, 3.22, 3.24, 3.26-3.30 распространяется от места установки знака до ближайшего перекрестка за ним, а в населенных пунктах при отсутствии перекрестка — до конца населенного пункта. Действие знаков не прерывается в местах выезда с прилегающих к дороге территорий.\n\nДействие знака 3.24, установленного перед населенным пунктом, обозначенным знаком 5.22, распространяется до этого знака.\n\nЗона действия знаков может быть уменьшена:\n\nдля знаков 3.16 и 3.26 применением таблички 7.2.1;\nдля знаков 3.20, 3.22, 3.24 установкой в конце зоны их действия соответственно знаков 3.21, 3.23, 3.25 или применением таблички 7.2.1. Зона действия знака 3.24 может быть уменьшена установкой знака 3.24 с другим значением максимальной скорости движения;\nдля знаков 3.27-3.30 установкой в конце зоны их действия повторных знаков 3.27-3.30 с табличкой 7.2.3 или применением таблички 7.2.2. Знак 3.27 может быть применен совместно с разметкой 1.4, а знак 3.28 — с разметкой 1.10, при этом зона действия знаков определяется протяженностью линии разметки.\nДействие знаков 3.10, 3.27-3.30 распространяется только на ту сторону дороги, на которой они установлены."}];
    [signsInfos addObject:@{TYPE_CODE:@"Information",  GROUP_INFO_TEXT: @"На знаках 5.20.1, 5.20.2, 5.21.1 и 5.21.2, установленных вне населенного пункта, зеленый или синий фон означает, что движение к указанному населенному пункту или объекту будет осуществляться соответственно по автомагистрали или другой дороге.\n\nНа знаках 5.20.1, 5.20.2, 5.21.1 и 5.21.2, установленных в населенном пункте, зеленый или синий фон означает, что движение к указанному населенному пункту или объекту после выезда из данного населенного пункта будет осуществляться соответственно по автомагистрали или другой дороге; белый фон означает, что указанный объект находится в данном населенном пункте."}];
    [signsInfos addObject:@{TYPE_CODE:@"Addition",  GROUP_INFO_TEXT: @"Таблички размещаются непосредственно под знаком, с которым они применены. Таблички 7.2.2-7.2.4, 7.13 при расположении знаков над проезжей частью, обочиной или тротуаром размещаются сбоку от знака."}];
    
    return [signsInfos copy];
}

+ (NSString *) getInfoForSignGroup:(NSString *)groupCode
{
    NSArray *allTheInfos = [self getAllTheSignsInfo];
    for (NSDictionary *currentInfo in allTheInfos)
    {
        if ([currentInfo[TYPE_CODE] isEqualToString:groupCode])
        {
            return currentInfo[GROUP_INFO_TEXT];
        }
    }
    
    return nil;
}

@end
