//
//  SignsData.m
//  TrafficLawsKazakhstan
//
//  Created by Eugene Rozhkov on 09.03.15.
//  Copyright (c) 2015 Nord Point. All rights reserved.
//

#import "SignsData.h"

@implementation SignsData

+ (NSArray *) getAllTheSigns
{
    NSMutableArray *allTheSigns = [@[] mutableCopy];
    
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Железнодорожный переезд со шлагбаумом»\n", SIGN_IMAGE_NAME: @"1_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.2", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Железнодорожный переезд без шлагбаума»\n", SIGN_IMAGE_NAME: @"1_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.3.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Однопутная железная дорога»\nОбозначение необорудованного шлагбаумом переезда через железную дорогу с одним путем", SIGN_IMAGE_NAME: @"1_3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.3.2", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Многопутная железная дорога»\nОбозначение необорудованного шлагбаумом переезда через железную дорогу с двумя путями и более.", SIGN_IMAGE_NAME: @"1_3_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Приближение к железнодорожному переезду»\nДополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.2", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Приближение к железнодорожному переезду»\nДополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.3", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Приближение к железнодорожному переезду»\nДополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.4", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Приближение к железнодорожному переезду»\nДополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.5", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Приближение к железнодорожному переезду»\nДополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.4.6", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Приближение к железнодорожному переезду»\nДополнительное предупреждение о приближении к железнодорожному переезду вне населенных пунктов.", SIGN_IMAGE_NAME: @"1_4_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.5", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Пересечение с трамвайной линией»\n", SIGN_IMAGE_NAME: @"1_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.6", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Пересечение равнозначных дорог»\n", SIGN_IMAGE_NAME: @"1_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.7", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Пересечение с круговым движением»\n", SIGN_IMAGE_NAME: @"1_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.8", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Светофорное регулирование»\nПерекресток, пешеходный переход или участок дороги, движение на котором регулируется светофором.", SIGN_IMAGE_NAME: @"1_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.9", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Разводной мост»\nРазводной мост или паромная переправа", SIGN_IMAGE_NAME: @"1_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.10", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Выезд на набережную»\nВыезд на набережную или берег.", SIGN_IMAGE_NAME: @"1_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.11.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Опасный поворот направо»\nЗакругление дороги малого радиуса или с ограниченной видимостью.", SIGN_IMAGE_NAME: @"1_11_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.11.2", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Опасный поворот налево»\nЗакругление дороги малого радиуса или с ограниченной видимостью.", SIGN_IMAGE_NAME: @"1_11_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.12.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Опасные повороты»\nУчасток дороги с опасными поворотами с первым поворотом направо.", SIGN_IMAGE_NAME: @"1_12_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.12.2", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Опасные повороты»\nУчасток дороги с опасными поворотами с первым поворотом налево.", SIGN_IMAGE_NAME: @"1_12_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.13", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Крутой спуск»\n", SIGN_IMAGE_NAME: @"1_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.14", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Крутой подъем»\n", SIGN_IMAGE_NAME: @"1_14.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.15", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Скользкая дорога»\nУчасток дороги с повышенной скользкостью проезжей части.", SIGN_IMAGE_NAME: @"1_15.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.16", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Неровная дорога»\nУчасток дороги, имеющий неровности на проезжей части (волнистость, выбоины, неплавные сопряжения с мостами и тому подобное).", SIGN_IMAGE_NAME: @"1_16.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.16.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Искусственная неровность»\n", SIGN_IMAGE_NAME: @"1_16_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.17", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Выброс гравия»\nУчасток дороги, на котором возможен выброс гравия, щебня и тому подобного из-под колес транспортных средств.", SIGN_IMAGE_NAME: @"1_17.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.18.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Сужение дороги»\nСужение с обеих сторон", SIGN_IMAGE_NAME: @"1_18_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.18.2", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Сужение дороги»\nСужение справа", SIGN_IMAGE_NAME: @"1_18_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.18.3", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Сужение дороги»\nСужение слева", SIGN_IMAGE_NAME: @"1_18_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.19", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Двустороннее движение»\nНачало участка дороги (проезжей части) с встречным движением.", SIGN_IMAGE_NAME: @"1_19.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.20", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Пешеходный переход»\nПешеходный переход, обозначенный знаками 5.16.1, 5.16.2и (или) разметкой 1.14.1, 1.14.2 или 1.14.3.", SIGN_IMAGE_NAME: @"1_20.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.21", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Дети»\nУчасток дороги вблизи детского учреждения (школы, оздоровительного лагеря и тому подобного), на проезжей части которого возможно появление детей.", SIGN_IMAGE_NAME: @"1_21.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.22", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Пересечение с велосипедной дорожкой»\n", SIGN_IMAGE_NAME: @"1_22.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.23", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Дорожные работы»\n", SIGN_IMAGE_NAME: @"1_23.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.24", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Перегон скота»\n", SIGN_IMAGE_NAME: @"1_24.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.25", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Дикие животные»\n", SIGN_IMAGE_NAME: @"1_25.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.26", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Падение камней»\nУчасток дороги, на котором возможны обвалы, оползни, падение камней.", SIGN_IMAGE_NAME: @"1_26.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.27", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Боковой ветер»\n", SIGN_IMAGE_NAME: @"1_27.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.28", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Низколетящие самолеты»\n", SIGN_IMAGE_NAME: @"1_28.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.29", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Тоннель»\nТоннель, в котором отсутствует искусственное освещение, или тоннель, видимость въездного портала которого ограничена.", SIGN_IMAGE_NAME: @"1_29.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.30", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Прочие опасности»\nУчасток дороги, на котором имеются опасности, не предусмотренные другими предупреждающими знаками.", SIGN_IMAGE_NAME: @"1_30.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Направление поворота»\nНаправление движения на закруглении дороги малого радиуса с ограниченной видимостью. Направление объезда ремонтируемого участка дороги.", SIGN_IMAGE_NAME: @"1_31_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.2", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Направление поворота»\nНаправление движения на закруглении дороги малого радиуса с ограниченной видимостью. Направление объезда ремонтируемого участка дороги.", SIGN_IMAGE_NAME: @"1_31_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.3", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Направление поворота»\nНаправления движения на Т-образном перекрестке или разветвлении дорог. Направления объезда ремонтируемого участка дороги.", SIGN_IMAGE_NAME: @"1_31_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.4", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Направление поворота»\n", SIGN_IMAGE_NAME: @"1_31_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.31.5", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Направление поворота»\n", SIGN_IMAGE_NAME: @"1_31_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.32.1", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Объезд препятствия»\n", SIGN_IMAGE_NAME: @"1_32_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.32.2", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Объезд препятствия»\n", SIGN_IMAGE_NAME: @"1_32_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"1.32.3", SIGN_TYPE:@"Warning", SIGN_DESCRIPTION: @"«Объезд препятствия»\n", SIGN_IMAGE_NAME: @"1_32_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.1", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Главная дорога».\nДорога, на которой предоставлено право преимущественного проезда нерегулируемых перекрестков.", SIGN_IMAGE_NAME: @"2_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.2", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Конец главной дороги».", SIGN_IMAGE_NAME: @"2_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.3.1", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Пересечение со второстепенной дорогой».", SIGN_IMAGE_NAME: @"2_3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.3.2", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Примыкание второстепенной дороги справа».", SIGN_IMAGE_NAME: @"2_3_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.3.3", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Примыкание второстепенной дороги слева».", SIGN_IMAGE_NAME: @"2_3_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.4", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Уступите дорогу».\nВодитель должен уступить дорогу транспортным средствам, движущимся по пересекаемой дороге, а при наличии таблички 7.13 — по главной.", SIGN_IMAGE_NAME: @"2_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.5", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Движение без остановки запрещено».\nЗапрещается движение без остановки перед стоп-линией, а если ее нет — перед краем пересекаемой проезжей части. Водитель должен уступить дорогу транспортным средствам, движущимся по пересекаемой дороге, а при наличии таблички 7.13 — по главной.\nЗнак 2.5 может быть установлен перед железнодорожным переездом или карантинным постом. В этих случаях водитель должен остановиться перед стоп-линией, а при ее отсутствии — перед знаком.", SIGN_IMAGE_NAME: @"2_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.6", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Преимущество встречного движения».\nЗапрещается въезд на узкий участок дороги, если это может затруднить встречное движение. Водитель должен уступить дорогу встречным транспортным средствам, находящимся на узком участке или противоположном подъезде к нему.", SIGN_IMAGE_NAME: @"2_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"2.7", SIGN_TYPE:@"Priority", SIGN_DESCRIPTION: @"«Преимущество перед встречным движением».\nУзкий участок дороги, при движении по которому водитель пользуется преимуществом по отношению к встречным транспортным средствам.", SIGN_IMAGE_NAME: @"2_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.1", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Въезд запрещен».\nЗапрещается въезд всех транспортных средств в данном направлении.", SIGN_IMAGE_NAME: @"3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.2", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение запрещено».\nЗапрещается движение всех транспортных средств.", SIGN_IMAGE_NAME: @"3_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.3", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение механических транспортных средств запрещено».", SIGN_IMAGE_NAME: @"3_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.4", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение грузовых автомобилей запрещено».\nЗапрещается движение грузовых автомобилей и составов транспортных средств с разрешенной максимальной массой более 3,5 т (если на знаке не указана масса) или с разрешенной максимальной массой более указанной на знаке, а также тракторов и самоходных машин.\nЗнак 3.4 не запрещает движение грузовых автомобилей с наклонной белой полосой на бортах или предназначенных для перевозки людей.", SIGN_IMAGE_NAME: @"3_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.5", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение мотоциклов запрещено».", SIGN_IMAGE_NAME: @"3_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.6", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение тракторов запрещено».\nЗапрещается движение тракторов и самоходных машин.", SIGN_IMAGE_NAME: @"3_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.7", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение транспортных средств с прицепом запрещено».", SIGN_IMAGE_NAME: @"3_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.8", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение гужевых повозок запрещено».\nЗапрещается движение гужевых повозок (саней), верховых и вьючных животных, а также прогон скота.", SIGN_IMAGE_NAME: @"3_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.9", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение на велосипедах запрещено».\nЗапрещается движение велосипедов и мопедов.", SIGN_IMAGE_NAME: @"3_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.10", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение пешеходов запрещено».", SIGN_IMAGE_NAME: @"3_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.11", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Ограничение массы».\nЗапрещается движение транспортных средств, в том числе составов транспортных средств, общая фактическая масса которых больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_11.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.12", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Ограничение нагрузки на ось».\nЗапрещается движение транспортных средств, у которых фактическая нагрузка на какую-либо ось больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_12.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.13", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Ограничение высоты».\nЗапрещается движение транспортных средств, габаритная высота которых (с грузом или без груза) больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.14", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Ограничение ширины».\nЗапрещается движение транспортных средств, габаритная ширина которых (с грузом или без груза) больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_14.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.15", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Ограничение длины».\nЗапрещается движение транспортных средств (составов транспортных средств), габаритная длина которых (с грузом или без груза) больше указанной на знаке.", SIGN_IMAGE_NAME: @"3_15.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.16", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Ограничение минимальной дистанции».\nЗапрещается движение транспортных средств с дистанцией между ними меньше указанной на знаке.", SIGN_IMAGE_NAME: @"3_16.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.17.1", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Таможня».\nЗапрещается проезд без остановки у таможни (контрольного пункта).", SIGN_IMAGE_NAME: @"3_17_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.17.2", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Опасность».\nЗапрещается дальнейшее движение всех без исключения транспортных средств в связи с дорожно-транспортным происшествием, аварией или другой опасностью.", SIGN_IMAGE_NAME: @"3_17_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.18.1", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Поворот направо запрещен».", SIGN_IMAGE_NAME: @"3_18_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.18.2", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Поворот налево запрещен».", SIGN_IMAGE_NAME: @"3_18_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.19", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Разворот запрещен».", SIGN_IMAGE_NAME: @"3_19.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.20", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Обгон запрещен».\nЗапрещается обгон всех транспортных средств, кроме одиночных, движущихся со скоростью менее 30 км/ч.", SIGN_IMAGE_NAME: @"3_20.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.21", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Конец зоны запрещения обгона».", SIGN_IMAGE_NAME: @"3_21.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.22", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Обгон грузовым автомобилям запрещен».\nЗапрещается грузовым автомобилям с разрешенной максимальной массой более 3,5 т обгон всех транспортных средств, кроме одиночных, движущихся со скоростью менее 30 км/ч. Тракторам запрещается обгон всех транспортных средств, кроме гужевых повозок и велосипедов.", SIGN_IMAGE_NAME: @"3_22.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.23", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Конец зоны запрещения обгона грузовым автомобилям».", SIGN_IMAGE_NAME: @"3_23.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.24", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Ограничение максимальной скорости».\nЗапрещается движение со скоростью (км/ч), превышающей указанную на знаке.", SIGN_IMAGE_NAME: @"3_24.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.25", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Конец зоны ограничения максимальной скорости».", SIGN_IMAGE_NAME: @"3_25.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.26", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Подача звукового сигнала запрещена».\nЗапрещается пользоваться звуковыми сигналами, кроме тех случаев, когда сигнал подается для предотвращения дорожно-транспортного происшествия.", SIGN_IMAGE_NAME: @"3_26.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.27", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Остановка запрещена».\nЗапрещаются остановка и стоянка транспортных средств.", SIGN_IMAGE_NAME: @"3_27.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.28", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Стоянка запрещена».\nЗапрещается стоянка транспортных средств.", SIGN_IMAGE_NAME: @"3_28.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.29", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Стоянка запрещена по нечетным числам месяца».\nПри одновременном применении знаков 3.29 и 3.30 время перестановки транспортных средств с одной стороны на другую — с 19 до 21 часа\n", SIGN_IMAGE_NAME: @"3_29.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.30", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Стоянка запрещена по четным числам месяца».\nПри одновременном применении знаков 3.29 и 3.30 время перестановки транспортных средств с одной стороны на другую — с 19 до 21 часа\n", SIGN_IMAGE_NAME: @"3_30.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.31", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Конец зоны всех ограничений».\nОбозначение конца зоны действия одновременно несколькими знаками из следующих: 3.16, 3.20, 3.22, 3.24, 3.26-3.30.", SIGN_IMAGE_NAME: @"3_31.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.32", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение транспортных средств с опасными грузами запрещено».\nЗапрещается движение транспортных средств, оборудованных опознавательными знаками «Опасный груз».", SIGN_IMAGE_NAME: @"3_32.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"3.33", SIGN_TYPE:@"Denial", SIGN_DESCRIPTION: @"«Движение транспортных средств со взрывчатыми и легковоспламеняющимися грузами запрещено».\nЗапрещается движение транспортных средств, оборудованных опознавательными знаками «Опасный груз» и предназначенных для перевозки опасных грузов классов 1,2.2-2.4, 3.1, 3.2, 5.2 по ГОСТу 19433-88.", SIGN_IMAGE_NAME: @"3_33.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.1", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Движение прямо».", SIGN_IMAGE_NAME: @"4_1_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.2", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Движение направо».", SIGN_IMAGE_NAME: @"4_1_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.3", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Движение налево».", SIGN_IMAGE_NAME: @"4_1_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.4", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Движение прямо или направо».", SIGN_IMAGE_NAME: @"4_1_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.5", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Движение прямо или налево».", SIGN_IMAGE_NAME: @"4_1_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.1.6", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Движение направо или налево».", SIGN_IMAGE_NAME: @"4_1_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.2.1", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Объезд препятствия справа».\nОбъезд разрешается только со стороны, указанной стрелкой.", SIGN_IMAGE_NAME: @"4_2_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.2.2", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Объезд препятствия слева».\nОбъезд разрешается только со стороны, указанной стрелкой.", SIGN_IMAGE_NAME: @"4_2_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.2.3", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Объезд препятствия справа или слева».\nОбъезд разрешается с любой стороны.", SIGN_IMAGE_NAME: @"4_2_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.3", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Круговое движение».\nРазрешается движение в указанном стрелками направлении.", SIGN_IMAGE_NAME: @"4_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.4", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Движение легковых автомобилей».\nРазрешается движение легковых автомобилей, автобусов, мотоциклов, маршрутных транспортных средств и грузовых автомобилей, разрешенная максимальная масса которых не превышает 3,5 т.\nЗнак разрешает движение и других транспортных средств, которые обслуживают предприятия, находящиеся в обозначенной зоне, а также обслуживают граждан или принадлежат гражданам, проживающим или работающим в обозначенной зоне. В этих случаях транспортные средства должны въезжать в обозначенную зону и выезжать из нее на ближайшем к месту назначения перекрестке.", SIGN_IMAGE_NAME: @"4_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.5", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Велосипедная дорожка».\nРазрешается движение только на велосипедах и мопедах. По велосипедной дорожке могут двигаться также пешеходы (при отсутствии тротуара, пешеходной дорожки или обочины).", SIGN_IMAGE_NAME: @"4_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.6", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Пешеходная дорожка».\nРазрешается движение только пешеходам.", SIGN_IMAGE_NAME: @"4_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.7", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Ограничение минимальной скорости».\nРазрешается движение только с указанной или большей скоростью (км/ч).", SIGN_IMAGE_NAME: @"4_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.8", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Конец зоны ограничения минимальной скорости».", SIGN_IMAGE_NAME: @"4_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.9.1", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Направление движения транспортных средств с опасными грузами».\nДвижение транспортных средств, оборудованных опознавательными знаками «Опасный груз», разрешается только направо.", SIGN_IMAGE_NAME: @"4_9_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.9.2", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Направление движения транспортных средств с опасными грузами».\nДвижение транспортных средств, оборудованных опознавательными знаками «Опасный груз», разрешается только налево.", SIGN_IMAGE_NAME: @"4_9_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"4.9.3", SIGN_TYPE:@"Dictating", SIGN_DESCRIPTION: @"«Направление движения транспортных средств с опасными грузами».\nДвижение транспортных средств, оборудованных опознавательными знаками «Опасный груз», разрешается только прямо.", SIGN_IMAGE_NAME: @"4_9_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Автомагистраль».\nДорога, на которой действуют требования Правил, устанавливающие порядок движения по автомагистралям.", SIGN_IMAGE_NAME: @"5_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец автомагистрали».", SIGN_IMAGE_NAME: @"5_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.3", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Дорога для автомобилей».\nДорога, предназначенная для движения только автомобилей и мотоциклов.", SIGN_IMAGE_NAME: @"5_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.4", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец дороги для автомобилей».", SIGN_IMAGE_NAME: @"5_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.5", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Дорога с односторонним движением».\nДорога или проезжая часть, по которой движение транспортных средств по всей ширине осуществляется в одном направлении.", SIGN_IMAGE_NAME: @"5_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.6", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец дороги с односторонним движением».", SIGN_IMAGE_NAME: @"5_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.7.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Выезд на дорогу с односторонним движением».\nВыезд на дорогу или проезжую часть с односторонним движением.\n", SIGN_IMAGE_NAME: @"5_7_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.7.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Выезд на дорогу с односторонним движением».\nВыезд на дорогу или проезжую часть с односторонним движением.\n", SIGN_IMAGE_NAME: @"5_7_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направления движения по полосам».\nЧисло полос и разрешенные направления движения на каждой из них.", SIGN_IMAGE_NAME: @"5_8_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направления движения по полосе».\nРазрешенные направления движения по полосе.\nЗнаки 5.8.1 и 5.8.2, разрешающие поворот налево из крайней левой полосы, разрешают и разворот с этой полосы.\nДействие знаков 5.8.1 и 5.8.2, установленных перед перекрестком, распространяется на весь перекресток, если другие знаки 5.8.1 и 5.8.2, установленные на нем, не дают иных указаний.", SIGN_IMAGE_NAME: @"5_8_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.3", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Начало полосы».\nНачало дополнительной полосы на подъеме или полосы торможения.\nЕсли на знаке, установленном перед дополнительной полосой, изображен знак 4.7 «Ограничение минимальной скорости», то водитель транспортного средства, который не может продолжать движение по основной полосе с указанной или большей скоростью, должен перестроиться на дополнительную полосу", SIGN_IMAGE_NAME: @"5_8_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.4", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Начало полосы».\nНачало участка средней полосы трехполосной дороги, предназначенного для движения в данном направлении.", SIGN_IMAGE_NAME: @"5_8_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.5", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец полосы».\nКонец дополнительной полосы на подъеме или полосы разгона.", SIGN_IMAGE_NAME: @"5_8_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.6", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец полосы».\nКонец участка средней полосы на трехполосной дороге, предназначенного для движения в данном направлении.", SIGN_IMAGE_NAME: @"5_8_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.7", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направление движения по полосам».\nЕсли на знаке 5.8.7 изображен знак, запрещающий движение каким-либо транспортным средствам, то движение этих транспортных средств по соответствующей полосе запрещается.\nЗнаки 5.8.7 и 5.8.8 с соответствующим числом стрелок могут применяться на дорогах с четырьмя полосами и более.\nС помощью знаков 5.8.7 и 5.8.8 со сменным изображением может быть организовано реверсивное движение.\n", SIGN_IMAGE_NAME: @"5_8_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.8.8", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направление движения по полосам».\nЕсли на знаке 5.8.7 изображен знак, запрещающий движение каким-либо транспортным средствам, то движение этих транспортных средств по соответствующей полосе запрещается.\nЗнаки 5.8.7 и 5.8.8 с соответствующим числом стрелок могут применяться на дорогах с четырьмя полосами и более.\nС помощью знаков 5.8.7 и 5.8.8 со сменным изображением может быть организовано реверсивное движение.\n", SIGN_IMAGE_NAME: @"5_8_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.9", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Полоса для маршрутных транспортных средств».\nПолоса, предназначенная для движения только маршрутных транспортных средств, движущихся попутно общему потоку транспортных средств.\nДействие знака распространяется на полосу, над которой он расположен. Действие знака, установленного справа от дороги, распространяется на правую полосу.", SIGN_IMAGE_NAME: @"5_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.10.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Дорога с полосой для маршрутных транспортных средств».\nДорога, по которой движение маршрутных транспортных средств осуществляется по специально выделенной полосе навстречу общему потоку транспортных средств.", SIGN_IMAGE_NAME: @"5_10_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.10.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Выезд на дорогу с полосой для маршрутных транспортных средств».\n", SIGN_IMAGE_NAME: @"5_10_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.10.3", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Выезд на дорогу с полосой для маршрутных транспортных средств».\n", SIGN_IMAGE_NAME: @"5_10_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.10.4", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец дороги с полосой для маршрутных транспортных средств».", SIGN_IMAGE_NAME: @"5_10_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.11.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Место для разворота».\nПоворот налево запрещается.", SIGN_IMAGE_NAME: @"5_11_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.11.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Зона для разворота».\nПротяженность зоны для разворота. Поворот налево запрещается.", SIGN_IMAGE_NAME: @"5_11_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.12", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Место остановки автобуса и (или) троллейбуса».", SIGN_IMAGE_NAME: @"5_12.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.13", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Место остановки трамвая».", SIGN_IMAGE_NAME: @"5_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.14", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Место стоянки легковых такси».", SIGN_IMAGE_NAME: @"5_14.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.15", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Место стоянки».", SIGN_IMAGE_NAME: @"5_15.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.16.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Пешеходный переход».\nПри отсутствии на переходе разметки 1.14.1, 1.14.2 или1.14.3 знак 5.16.2 устанавливается справа от дороги на ближней границе перехода, а знак 5.16.1 — слева от дороги на дальней границе перехода.\n", SIGN_IMAGE_NAME: @"5_16_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.16.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Пешеходный переход».\nПри отсутствии на переходе разметки 1.14.1, 1.14.2 или1.14.3 знак 5.16.2 устанавливается справа от дороги на ближней границе перехода, а знак 5.16.1 — слева от дороги на дальней границе перехода.\n", SIGN_IMAGE_NAME: @"5_16_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.17.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Подземный пешеходный переход».\n", SIGN_IMAGE_NAME: @"5_17_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.17.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Подземный пешеходный переход».\n", SIGN_IMAGE_NAME: @"5_17_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.17.3", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Надземный пешеходный переход».\n", SIGN_IMAGE_NAME: @"5_17_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.17.4", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Надземный пешеходный переход».\n", SIGN_IMAGE_NAME: @"5_17_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.18", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Рекомендуемая скорость».\nСкорость, с которой рекомендуется движение на данном участке дороги. Зона действия знака распространяется до ближайшего перекрестка, а при применении знака 5.18 совместно с предупреждающим знаком определяется протяженностью опасного участка.", SIGN_IMAGE_NAME: @"5_18.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.19.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Тупик».\nДорога, не имеющая сквозной проезд.\n", SIGN_IMAGE_NAME: @"5_19_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.19.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Тупик».\nДорога, не имеющая сквозной проезд.\n", SIGN_IMAGE_NAME: @"5_19_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.19.3", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Тупик».\nДорога, не имеющая сквозной проезд.\n", SIGN_IMAGE_NAME: @"5_19_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.20.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Предварительный указатель направления».\nНаправления движения к обозначенным на знаке населенным пунктам и другим объектам. На знаках могут быть нанесены изображения знака 5.29.1, символы автомагистрали, аэропорта, спортивные и иные пиктограммы.\nНа знаке 5.20.1 могут быть нанесены изображения других знаков, информирующих об особенностях движения. В нижней части знака 5.20.1 указывается расстояние от места установки знака до перекрестка или начала полосы торможения.\nЗнак 5.20.1 применяется также для указания объезда участков дорог, на которых установлен один из запрещающих знаков 3.11-3.15.", SIGN_IMAGE_NAME: @"5_20_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.20.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Предварительный указатель направления».\nНаправления движения к обозначенным на знаке населенным пунктам и другим объектам. На знаках могут быть нанесены изображения знака 5.29.1, символы автомагистрали, аэропорта, спортивные и иные пиктограммы.\nНа знаке 5.20.1 могут быть нанесены изображения других знаков, информирующих об особенностях движения. В нижней части знака 5.20.1 указывается расстояние от места установки знака до перекрестка или начала полосы торможения.\nЗнак 5.20.1 применяется также для указания объезда участков дорог, на которых установлен один из запрещающих знаков 3.11-3.15.", SIGN_IMAGE_NAME: @"5_20_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.20.3", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Схема движения».\nМаршрут движения при запрещении на перекрестке отдельных маневров или разрешенные направления движения на сложном перекрестке.", SIGN_IMAGE_NAME: @"5_20_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.21.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Указатель направлений».\nНаправления движения к пунктам маршрута. На знаках может быть указано расстояние до обозначенных на нем объектов (км), нанесены символы автомагистрали, аэропорта, спортивные и иные пиктограммы.", SIGN_IMAGE_NAME: @"5_21_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.21.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Указатель направлений».\nНаправления движения к пунктам маршрута. На знаках может быть указано расстояние до обозначенных на нем объектов (км), нанесены символы автомагистрали, аэропорта, спортивные и иные пиктограммы.", SIGN_IMAGE_NAME: @"5_21_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.22", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Начало населенного пункта».\nНаименование и начало населенного пункта, в котором действуют требования Правил, устанавливающие порядок движения в населенных пунктах.", SIGN_IMAGE_NAME: @"5_22.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.23", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец населенного пункта».\nМесто, с которого на данной дороге утрачивают силу требования Правил, устанавливающие порядок движения в населенных пунктах.", SIGN_IMAGE_NAME: @"5_23.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.24", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Начало населенного пункта».\nНаименование и начало населенного пункта, в котором на данной дороге не действуют требования Правил, устанавливающие порядок движения в населенных пунктах.", SIGN_IMAGE_NAME: @"5_24.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.25", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец населенного пункта».\nКонец населенного пункта, обозначенного знаком 5.24.", SIGN_IMAGE_NAME: @"5_25.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.26", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Наименование объекта».\nНаименование объекта иного, чем населенный пункт (река, озеро, перевал, достопримечательность и тому подобное).", SIGN_IMAGE_NAME: @"5_26.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.27", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Указатель расстояний».\nРасстояние до населенных пунктов (км), расположенных на маршруте.", SIGN_IMAGE_NAME: @"5_27.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.28", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Километровый знак».\nРасстояние до начала или конца дороги (км).", SIGN_IMAGE_NAME: @"5_28.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.29.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Номер маршрута».\nНомер, присвоенный дороге (маршруту).", SIGN_IMAGE_NAME: @"5_29_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.29.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Номер маршрута».\nНомер и направление дороги (маршрута).", SIGN_IMAGE_NAME: @"5_29_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.30.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направление движения для грузовых автомобилей».\nРекомендуемое направление движения для грузовых автомобилей, тракторов и самоходных машин, если на перекрестке их движение в одном из направлений запрещено.\n", SIGN_IMAGE_NAME: @"5_30_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.30.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направление движения для грузовых автомобилей».\nРекомендуемое направление движения для грузовых автомобилей, тракторов и самоходных машин, если на перекрестке их движение в одном из направлений запрещено.\n", SIGN_IMAGE_NAME: @"5_30_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.30.3", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направление движения для грузовых автомобилей».\nРекомендуемое направление движения для грузовых автомобилей, тракторов и самоходных машин, если на перекрестке их движение в одном из направлений запрещено.\n", SIGN_IMAGE_NAME: @"5_30_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.31", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Схема объезда».\nМаршрут объезда участка дороги, временно закрытого для движения.", SIGN_IMAGE_NAME: @"5_31.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.32.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направление объезда».\nНаправление участка дороги, временно закрытого для движения.\n", SIGN_IMAGE_NAME: @"5_32_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.32.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направление объезда».\nНаправление участка дороги, временно закрытого для движения.\n", SIGN_IMAGE_NAME: @"5_32_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.32.3", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Направление объезда».\nНаправление участка дороги, временно закрытого для движения.\n", SIGN_IMAGE_NAME: @"5_32_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.33", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Стоп-линия».\nМесто остановки транспортных средств при запрещающем сигнале светофора (регулировщика).", SIGN_IMAGE_NAME: @"5_33.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.34.1", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Предварительный указатель перестроения на другую проезжую часть».\nНаправление объезда закрытого для движения участка проезжей части на дороге с разделительной полосой или направление движения для возвращения на правую проезжую часть.\n", SIGN_IMAGE_NAME: @"5_34_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.34.2", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Предварительный указатель перестроения на другую проезжую часть».\nНаправление объезда закрытого для движения участка проезжей части на дороге с разделительной полосой или направление движения для возвращения на правую проезжую часть.\n", SIGN_IMAGE_NAME: @"5_34_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.35", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Реверсивное движение».\nНачало участка дороги, на котором на одной или нескольких полосах направление движения может изменяться на противоположное.", SIGN_IMAGE_NAME: @"5_35.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.36", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец реверсивного движения».", SIGN_IMAGE_NAME: @"5_36.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.37", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Выезд на дорогу с реверсивным движением».", SIGN_IMAGE_NAME: @"5_37.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.38", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Жилая зона».\nТерритория, на которой действуют требования Правил, устанавливающие порядок движения в жилой зоне.", SIGN_IMAGE_NAME: @"5_38.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"5.39", SIGN_TYPE:@"Information", SIGN_DESCRIPTION: @"«Конец жилой зоны».", SIGN_IMAGE_NAME: @"5_39.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.1", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Пункт первой медицинской помощи».", SIGN_IMAGE_NAME: @"6_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.2", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Больница».", SIGN_IMAGE_NAME: @"6_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.3", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Автозаправочная станция».", SIGN_IMAGE_NAME: @"6_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.4", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Техническое обслуживание автомобилей».", SIGN_IMAGE_NAME: @"6_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.5", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Мойка автомобилей».", SIGN_IMAGE_NAME: @"6_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.6", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Телефон».", SIGN_IMAGE_NAME: @"6_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.7", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Пункт питания».", SIGN_IMAGE_NAME: @"6_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.8", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Питьевая вода».", SIGN_IMAGE_NAME: @"6_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.9", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Гостиница или мотель».", SIGN_IMAGE_NAME: @"6_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.10", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Кемпинг».", SIGN_IMAGE_NAME: @"6_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.11", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Место отдыха».", SIGN_IMAGE_NAME: @"6_11.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.12", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Пост дорожной полиции».", SIGN_IMAGE_NAME: @"6_12.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"6.13", SIGN_TYPE:@"Service", SIGN_DESCRIPTION: @"«Пост транспортного контроля».", SIGN_IMAGE_NAME: @"6_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.1.1", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Расстояние до объекта».\nУказывается расстояние от знака до начала опасного участка, места введения соответствующего ограничения или определенного объекта (места), находящегося впереди по ходу движения.", SIGN_IMAGE_NAME: @"7_1_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.1.2", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Расстояние до объекта».\nУказывает расстояние от знака 2.4 до перекрестка в случае, если непосредственно перед перекрестком установлен знак 2.5.", SIGN_IMAGE_NAME: @"7_1_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.1.3", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Расстояние до объекта».\nУказывает расстояние до объекта, находящегося в стороне от дороги.", SIGN_IMAGE_NAME: @"7_1_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.1.4", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Расстояние до объекта».\nУказывает расстояние до объекта, находящегося в стороне от дороги.", SIGN_IMAGE_NAME: @"7_1_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.1", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Зона действия».\nУказывает протяженность опасного участка дороги, обозначенного знаками, или зону действия запрещающих и информационно-указательных знаков.", SIGN_IMAGE_NAME: @"7_2_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.2", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Зона действия».\nУказывает зону действия запрещающих знаков 3.27, 3.28, 3.29 и 3.30.", SIGN_IMAGE_NAME: @"7_2_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.3", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Зона действия».\nУказывает конец зоны действия знаков 3.27, 3.28, 3.29 и 3.30.", SIGN_IMAGE_NAME: @"7_2_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.4", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Зона действия».\nИнформирует водителей о нахождении их в зоне действия знаков 3.27,3.28, 3.29 и 3.30.", SIGN_IMAGE_NAME: @"7_2_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.5", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Зона действия».\nУказывают направление и зону действия знаков 3.27, 3.28, 3.29 и 3.30при запрещении остановки или стоянки вдоль одной стороны площади, фасада здания и тому подобного.", SIGN_IMAGE_NAME: @"7_2_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.2.6", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Зона действия».\nУказывают направление и зону действия знаков 3.27, 3.28, 3.29 и 3.30при запрещении остановки или стоянки вдоль одной стороны площади, фасада здания и тому подобного.", SIGN_IMAGE_NAME: @"7_2_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.3.1", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Направления действия».\nУказывают направления действия знаков, установленных перед перекрестком, или направления движения к обозначенным объектам, находящимся непосредственно у дороги.", SIGN_IMAGE_NAME: @"7_3_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.3.2", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Направления действия».\nУказывают направления действия знаков, установленных перед перекрестком, или направления движения к обозначенным объектам, находящимся непосредственно у дороги.", SIGN_IMAGE_NAME: @"7_3_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.3.3", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Направления действия».\nУказывают направления действия знаков, установленных перед перекрестком, или направления движения к обозначенным объектам, находящимся непосредственно у дороги.", SIGN_IMAGE_NAME: @"7_3_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.1", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Вид транспортного средства».\nУказывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.2", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Вид транспортного средства».\nУказывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.3", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Вид транспортного средства».\nУказывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.4", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Вид транспортного средства».\nУказывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.5", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Вид транспортного средства».\nУказывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.6", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Вид транспортного средства».\nУказывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.7", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Вид транспортного средства».\nУказывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.4.8", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Вид транспортного средства».\nУказывают вид транспортного средства, на который распространяется действие знака.\nТабличка 7.4.1 распространяет действие знака на грузовые автомобили, а табличка 7.4.2 в том числе и с прицепом, с разрешенной максимальной массой более 3,5 т;\nтабличка 7.4.3 — на легковые автомобили, а также грузовые автомобили с разрешенной максимальной массой до 3,5 т;\nтабличка 7.4.8 — на транспортные средства, оборудованные опознавательными знаками «Опасный груз»", SIGN_IMAGE_NAME: @"7_4_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.1", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Субботние, воскресные и праздничные дни».\nУказывают дни недели, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.2", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Рабочие дни».\nУказывают дни недели, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.3", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Дни недели».\nУказывают дни недели, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.4", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Время действия».\nУказывает время суток, в течение которого действует знак.", SIGN_IMAGE_NAME: @"7_5_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.5", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Время действия».\nУказывают дни недели и время суток, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.6", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Время действия».\nУказывают дни недели и время суток, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.5.7", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Время действия».\nУказывают дни недели и время суток, в течение которых действует знак.", SIGN_IMAGE_NAME: @"7_5_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.1", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_1.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.2", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_2.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.3", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_3.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.4", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_4.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.5", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_5.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.6", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_6.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.7", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.8", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.6.9", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Способ постановки транспортного средства на стоянку».\n7.6.1 указывает, что все транспортные средства должны быть поставлены на проезжей части вдоль тротуара;\n7.6.2-7.6.9 указывают способ постановки легковых автомобилей и мотоциклов на околотротуарной стоянке.\nПрименяются со знаком 5.15.", SIGN_IMAGE_NAME: @"7_6_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.7", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Стоянка с неработающим двигателем».\nУказывает, что на стоянке, обозначенной знаком 5.15, разрешается стоянка транспортных средств только с неработающим двигателем.", SIGN_IMAGE_NAME: @"7_7.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.8", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Платные услуги».\nУказывает, что услуги предоставляются только за оплату.", SIGN_IMAGE_NAME: @"7_8.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.9", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Ограничение продолжительности стоянки».\nУказывает максимальную продолжительность пребывания транспортного средства на стоянке, обозначенной знаком 5.15.", SIGN_IMAGE_NAME: @"7_9.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.10", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Место для осмотра автомобилей».\nУказывает, что на площадке, обозначенной знаком 5.15 или 6.11, имеется эстакада или смотровая канава.", SIGN_IMAGE_NAME: @"7_10.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.11", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Ограничение полной массы».\nУказывает, что действие знака распространяется только на транспортные средства с разрешенной максимальной массой более указанной на табличке.", SIGN_IMAGE_NAME: @"7_11.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.12", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Опасная обочина».\nПредупреждает, что съезд на обочину опасен в связи с проведением на ней ремонтных работ. Применяется со знаком 1.23.", SIGN_IMAGE_NAME: @"7_12.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.13", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Направление главной дороги».\nУказывает направление главной дороги на перекрестке.", SIGN_IMAGE_NAME: @"7_13.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.14", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Полоса движения».\nУказывает полосу движения, на которую распространяется действие знака или светофора.", SIGN_IMAGE_NAME: @"7_14.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.15", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Слепые пешеходы».\nУказывает, что пешеходным переходом пользуются слепые. Применяется со знаками 1.20, 5.16.1, 5.16.2 и светофорами.", SIGN_IMAGE_NAME: @"7_15.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.16", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Влажное покрытие».\nУказывает, что действие знака распространяется на период времени, когда покрытие проезжей части влажное.", SIGN_IMAGE_NAME: @"7_16.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.17", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Инвалиды».\nУказывает, что действие знака 5.15 распространяется только на мотоколяски и автомобили, на которых установлены опознавательные знаки «Инвалид»", SIGN_IMAGE_NAME: @"7_17.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.18", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Кроме инвалидов».\nУказывает, что действие знаков не распространяется на мотоколяски и автомобили, на которых установлены опознавательные знаки «Инвалид»", SIGN_IMAGE_NAME: @"7_18.png"}];
    [allTheSigns addObject:@{SIGN_NUMBER: @"7.19", SIGN_TYPE:@"Addition", SIGN_DESCRIPTION: @"«Класс опасного груза».\nУказывает номер класса (классов) опасных грузов по ГОСТу 19433-88. Применяется со знаками 3.32, 4.9.1-4.9.3\n", SIGN_IMAGE_NAME: @"7_19.png"}];

    
    return [allTheSigns copy];
}

+ (NSArray *) getWarningSigns
{
    NSMutableArray *warningSigns = [@[] mutableCopy];
    
    for (NSDictionary *currentSign in [self getAllTheSigns])
    {
        if ([currentSign[SIGN_TYPE] isEqualToString:@"Warning"])
             {
                 [warningSigns addObject:currentSign];
             }
    }
    
    return [warningSigns copy];
}

+ (NSDictionary *) getSignWithNumber:(NSString *)signNumber
{
    NSArray *allTheSigns = [self getAllTheSigns];
    for (NSDictionary *currentSign in allTheSigns)
    {
        if ([currentSign[SIGN_NUMBER] isEqualToString:signNumber])
        {
            return currentSign;
        }
    }
    
    return nil;
}

@end
